daysUnitilStale: 240
daysUnitilClose: 30
exemptLabels:
  - pinned
  - security
  - discussion
staleLabel: wontfix
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: false